### ISSUE TITLE
"tls handshake eof" when connect to Azure IoT Hub as MQTT client

### ISSUE THREAD

**Issue by xudesheng** [fluffysquirrels/mqtt-async-client-rs#13]
`
fn iothub_tls_client(host:&str, port:u16, clientid:&str, username:&str,password:&str) -> Result<Client> {
    let mut cc = rustls::ClientConfig::new();
    //let cert_bytes = include_bytes!("../../certs/BaltimoreCyberTrustRoot.crt.pem");
    let ca_file="../certs/BaltimoreCyberTrustRoot.crt.pem";
    // let cert_bytes = std::fs::read(ca_file)?;
    // let cert = rustls::internal::pemfile::certs(&mut Cursor::new(&cert_bytes[..]))
    //     .map_err(|_| Error::from("Error parsing cert file"))?[0].clone();
    //println!("cert loaded: {:?}", cert);
    let mut pem = BufReader::new(File::open(ca_file)?);

    // cc.root_store.add(&cert)
    //     .map_err(|e| Error::from_std_err(e))?;
    cc.root_store.add_pem_file(&mut pem)
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "invalid cert"))?;
    println!("root store added.");

    Client::builder()
        .set_host(host.to_owned())
        .set_port(port)
        .set_client_id(Some(clientid.to_owned()))
        .set_username(Some(username.to_owned()))
        .set_password(Some(password.to_owned().as_bytes().to_vec()))
        .set_tls_client_config(cc)
        .set_connect_retry_delay(Duration::from_secs(2))
        .build()
}`

Error message:
2020-02-24T04:23:02Z ERROR mqtt_async_client::client::client] IoTask: Error connecting: tls handshake eof

this piece of code basically is copied from your test code and I have tried different way but always stuck there with same error message during publish.

**Comment by fluffysquirrels** [comment]
Hi, thanks for your interest in the crate!

I want to try connecting myself. Which host and port are you connecting to?

**Comment by xudesheng** [comment]
Hi, @fluffysquirrels , the host I'm trying to connect is: `dxuiothub.azure-devices.net` on port 8883, I have used Python Paho MQTT to test and it works as expected.

**Comment by fluffysquirrels** [comment]
I just had the chance to try it myself and get the same error. The openssl test client does work (`openssl s_client -connect dxuiothub.azure-devices.net:8883` if you have openssl installed) and it selects the cipher `ECDHE-RSA-AES128-SHA256`, which `rustls` (the TLS crate we use) doesn't support.

I tried looking at the Azure documentation to see which ciphers they claim to support and found [this page](https://docs.microsoft.com/en-gb/azure/iot-hub/iot-hub-tls-support), which claims to support `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`, amongst others, but I can't get the openssl test client to connect with that cipher (`openssl s_client -connect dxuiothub.azure-devices.net:8883 -debug -cipher ECDHE-RSA-AES128-GCM-SHA256` fails but `openssl s_client -connect dxuiothub.azure-devices.net:8883 -debug -cipher ECDHE-RSA-AES128-SHA256` succeeds)

At this point I'd reach out to Microsoft if you can to see if they can shed any light on why you can't connect with what they claim are supported ciphers.

**Comment by xudesheng** [comment]
@fluffysquirrels thank you!!!
I will try on my end to see what's the reason behind that.

Is it possible to enhance your lib and support openssl?

**Comment by fluffysquirrels** [comment]
From the Azure docs it should be possible to find a cipher that works.

Failing that, I can consider adding support for openssl.

**Comment by xudesheng** [comment]
@fluffysquirrels thank you. I already reported this to Azure and usually they will come back within few hours.

appreciate if you can add openssl support but I understand that it may need extra effort to handle openssl compiling.

**Comment by fluffysquirrels** [comment]
Thanks for contacting Azure.

Compiling OpenSSL is actually handled rather nicely by the `openssl` crate. The 2 problems are: 1) the rather messy interface left in the library if you want to support both (see hyper); and 2) part of the goal of this crate was to offer a pure-ish Rust MQTT client, but including OpenSSL (with its ~600k lines of C) seems somewhat contrary to that goal.

**Comment by xudesheng** [comment]
@fluffysquirrels thank you for your response. fully understood and agreed. I will wait for them for days and I can try using openssl by my own as workaround if no progress. No need to modify current crate.

**Comment by xudesheng** [comment]
Hi, @fluffysquirrels , just got feedback from Azure:
1) they will update document soon.
2) However, cipher "ECDHE-RSA-AES128-SHA256" indeed is the third one listed in the document you mentioned above. It's just a different naming according to: https://wiki.mozilla.org/Security/Cipher_Suites

if so, could you please kindly take a look why this crate didn't pickup cipher "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256" or "ECDHE-RSA-AES128-SHA256"?

thanks.

**Comment by fluffysquirrels** [comment]
`rustls` is the crate I currently use for TLS, and it doesn't support AES-CBC modes; I believe this is deliberate because there have been recent attacks against CBC modes. 

If you view the trace level logs (e.g. with `RUST_LOG="trace" cargo run --bin mqttc -- --host dxuiothub.azure-devices.net --port 8883 --tls-mozilla-root-cas publish a b`) you'll see the ciphers this crate is advertising:

```
TLS13_CHACHA20_POLY1305_SHA256,
TLS13_AES_256_GCM_SHA384,nel.
TLS13_AES_128_GCM_SHA256,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
```

It's  a bit of a shame that Azure are updating their documents instead of supporting the cipher they advertise, but that is the easiest fix for them.

In case it helps, you can use [`stunnel`](https://www.stunnel.org/) (which uses openssl) to do TLS termination for you. I ran `stunnel stunnel.conf`, with `stunnel.conf`:
```
foreground = yes
debug = debug

[dx]
client = yes
accept = 127.0.0.1:1234
connect = dxuiothub.azure-devices.net:8883
```
and then connected with the mqtt crate to `localhost:1234` with no encryption. Seems to work fine.

**Comment by fluffysquirrels** [comment]
I created issue #14: "Support openssl for TLS" for you to see if I eventually get around to supporting openssl.

**Comment by xudesheng** [comment]
@fluffysquirrels thank you! it's very helpful.

I will mask host name from my comment as xxx.com :)

**Comment by vipeller** [comment]
In case someone runs into this problem: as of today (10//20/2021) if you create your hub the way that it accepts only TLS 1.2, then you will have GCM support, so this can work:

openssl s_client -connect your_tls1_2_hub.azure-devices.net -port 8883 -cipher ECDHE-RSA-AES128-GCM-SHA256

When you create your hub, choose the "management" tab and at the end of the screen you can find the setting:

![image](https://user-images.githubusercontent.com/51135538/138184487-813d4d8d-afde-44a6-9769-997bdaa67085.png)

**Comment by fluffysquirrels** [comment]
@vipeller, thanks for looking into this! Glad we could find a way to make this work with Azure.
