### ISSUE TITLE
multi-clients support issue: `std::cell::RefCell<mqtt_async_client::util::free_pid_list::FreePidList>`

### ISSUE THREAD

**Issue by xudesheng** [fluffysquirrels/mqtt-async-client-rs#15]
I want to build a simulator which simulates multiple mqtt clients in async mode.
However, thread::spawn was blocked by "`std::cell::RefCell<mqtt_async_client::util::free_pid_list::FreePidList>`" since the trait `std::marker::Sync` is not implemented for it.

**Comment by fluffysquirrels** [comment]
Are you trying to call the same `Client` from multiple threads at the same time? I probably won't support that.

Can you use multiple `Client`s, one in each thread?

If you need `Client` to be `Send` then I can maybe support this.

**Comment by xudesheng** [comment]
> Are you trying to call the same `Client` from multiple threads at the same time? I probably won't support that.
> 
> Can you use multiple `Client`s, one in each thread?
> 
> If you need `Client` to be `Send` then I can maybe support this.

I'm not trying to call same client multiple time. Instead, I'm trying to simulate many MQTT clients and therefore `Client` has to support `Send`.
My current workaround is to lunch multiple threads and then use tokio::localset to execute future.

appreciate if you can support `Send`, then I don't need to manage how many threads I can lunch and how many clients have to be put into one thread.

Thank.

**Comment by fluffysquirrels** [comment]
I just pushed a change that I think made Client Send. Can you try 6010ac6c5c87c10a418994a5c353f387b9adfd54 and see if that fixes your build error?

**Comment by xudesheng** [comment]
> I just pushed a change that I think made Client Send. Can you try [6010ac6](https://github.com/fluffysquirrels/mqtt-async-client-rs/commit/6010ac6c5c87c10a418994a5c353f387b9adfd54) and see if that fixes your build error?

@fluffysquirrels Thank you, I can confirm it works.

once you released it, I will try to compare the performance between:
1) Using Tokio:spawn (with your updated lib)
2) Using Thread + tokio:LocalSet (with old lib).

**Comment by jkfritcher** [comment]
I got bit by this recently with tokio tasks, and after building the 6010ac6 revision mentioned above, it resolved my problem. This issue is 6+ months old, will a new release be made with this fix incorporated?

Thanks!

**Comment by fluffysquirrels** [comment]
@jkfritcher @xudesheng I just released 0.1.6 to crates.io. Sorry for the delay on this.

**Comment by fluffysquirrels** [comment]
I'll close this now since I think the fix works, happy for you to reopen it if there are more problems.
