### ISSUE TITLE
[enhancement] x.509 certificate support.

### ISSUE THREAD

**Issue by awsa2ron** [fluffysquirrels/mqtt-async-client-rs#25]
Any plan for x.509 certificate supporting?

**Comment by fluffysquirrels** [comment]
Hi! What kind of x.509 support are you interested in?

The `ClientBuilder.set_tls_client_config` takes a [`rustls::ClientConfig`](https://docs.rs/rustls/0.19.1/rustls/struct.ClientConfig.html), which supports many kinds of TLS cert configuration, including a server certificate root store and client certificates.

If those are the features you need, do you think the docs or examples need to be better for users to discover these features?

**Comment by awsa2ron** [comment]
Yes, I think a mutually authenticated TLS connection example would better for users. For example, aws IoT broker or other pravite/certificate authenticate broker.

**Comment by fluffysquirrels** [comment]
v0.3.1 contains updated documentation on [ClientBuilder](https://docs.rs/mqtt-async-client/0.3.1/mqtt_async_client/client/struct.ClientBuilder.html) with instructions on which items to use on `rustls::ClientConfig` to configure client and server TLS. I also reference our example `mqttc` which includes usage of both of these (added recently).

I hope these features and docs meet your needs.

**Comment by fluffysquirrels** [comment]
Closing this for now but feel free to re-open or create a new issue if you have more suggestions.
