### ISSUE TITLE
ConnectionMode is not exposed

### ISSUE THREAD

**Issue by marcelbuesing** [fluffysquirrels/mqtt-async-client-rs#26]
The `ConnectionMode` enum is not exposed and probably should be or set_connection_mode should be private.

https://docs.rs/mqtt-async-client/0.3.1/mqtt_async_client/client/struct.ClientBuilder.html#method.set_connection_mode

**Comment by fluffysquirrels** [comment]
Hmmm, my inclination is to make `set_connection_mode` private as we already let the user configure this through their choice of URL and allowing them to configure through both might be confusing.

**Comment by marcelbuesing** [comment]
Yes I agree. I think even better is to remove the function for now. It's apparently not being used anywhere internally in the code, other functions directly set the field. I have updated the PR, feel free to also just change it like that and close the PR.

**Comment by fluffysquirrels** [comment]
Looks good, thanks for this.
